var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(public)/services/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0p2gage._.js")
R.c("server/chunks/ssr/node_modules_next_dist_1n3w9lb._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0mud04e._.js")
R.c("server/chunks/ssr/[root-of-the-server]__15y_puz._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0j26pto._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1pxmsu2._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0q-w892.js")
R.c("server/chunks/ssr/_0r8x4dv._.js")
R.c("server/chunks/ssr/_next-internal_server_app_(public)_services_page_actions_0n48r7h.js")
R.m(41582)
module.exports=R.m(41582).exports
