var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(public)/about/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__03as17x._.js")
R.c("server/chunks/ssr/node_modules_next_dist_1n3w9lb._.js")
R.c("server/chunks/ssr/_1jk2kpd._.js")
R.c("server/chunks/ssr/[root-of-the-server]__15y_puz._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0j26pto._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1pxmsu2._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0q-w892.js")
R.c("server/chunks/ssr/_0r8x4dv._.js")
R.c("server/chunks/ssr/_next-internal_server_app_(public)_about_page_actions_09l--rg.js")
R.m(78713)
module.exports=R.m(78713).exports
